<?php 

class ArisCollection extends Entity {

}

class ArisCollectionModelController extends EntityApiController{

    public function create(array $values = [])
    {
        global $user;

        $values += [
            'type' => 'aris_collection',
            'uid' => $user->uid,
            'gid' => 0
        ];
        return parent::create($values);
    }

    public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
        $wrapper = entity_metadata_wrapper('aris_collection', $entity);
        $content['author'] = array('#markup' => t('Created by: !author', array('!author' => $wrapper->uid->name->value(array('sanitize' => TRUE)))));

        // Make Description and Status themed like default fields.
        $content['description'] = array(
            '#theme' => 'field',
            '#weight' => 0,
            '#title' =>t('Description'),
            '#access' => TRUE,
            '#label_display' => 'above',
            '#view_mode' => 'full',
            '#language' => LANGUAGE_NONE,
            '#field_name' => 'field_fake_description',
            '#field_type' => 'text',
            '#entity_type' => 'example_task',
            '#bundle' => $entity->type,
            '#items' => array(array('value' => $entity->description)),
            '#formatter' => 'text_default',
            0 => array('#markup' => check_plain($entity->description))
        );

        return parent::buildContent($entity, $view_mode, $langcode, $content);
    }

  /**
   * @inheritDoc
   */
  public function load($ids = array() , $conditions = array())
  {
    $parent =  parent::load($ids , $conditions);
    $group = [];
    foreach ($parent as $item){
      $item->type = 'aris_group';
      $group[$item->gid] = $item;
    }
    return $group;
  }

  /**
   * @inheritDoc
   */
  public function delete($ids , DatabaseTransaction $transaction = NULL)
  {
    return parent::delete($ids , $transaction); // TODO: Change the autogenerated stub
  }


}
